/**
 * BranchPixelIcon — vendored from the HackerNoon Pixel Icon Library ("branch", regular).
 *
 * Generated by `scripts/vendor-pixel-icons.mjs`. Do not edit by hand.
 * Artwork licensed CC BY 4.0 — see `docs/third-party-notices.md`.
 */
import type { PixelIconProps } from '../types'

export function BranchPixelIcon({ size = 16, ...props }: PixelIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path d="M20,2V1H16V2H15V6h1V7h1v4H7V7H8V6H9V2H8V1H4V2H3V6H4V7H5V17H4v1H3v4H4v1H8V22H9V18H8V17H7V13H19V7h1V6h1V2ZM5,3H7V5H5ZM7,21H5V19H7ZM19,5H17V3h2Z" />
    </svg>
  )
}
