/**
 * EllipsesHorizontalPixelIcon — vendored from the HackerNoon Pixel Icon Library ("ellipses-horizontal", regular).
 *
 * Generated by `scripts/vendor-pixel-icons.mjs`. Do not edit by hand.
 * Artwork licensed CC BY 4.0 — see `docs/third-party-notices.md`.
 */
import type { PixelIconProps } from '../types'

export function EllipsesHorizontalPixelIcon({ size = 16, ...props }: PixelIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path d="m6,10h-1v-1h-2v1h-1v1h-1v2h1v1h1v1h2v-1h1v-1h1v-2h-1v-1Zm-1,3h-2v-2h2v2Z" />
      <path d="m14,10h-1v-1h-2v1h-1v1h-1v2h1v1h1v1h2v-1h1v-1h1v-2h-1v-1Zm-1,3h-2v-2h2v2Z" />
      <path d="m22,11v-1h-1v-1h-2v1h-1v1h-1v2h1v1h1v1h2v-1h1v-1h1v-2h-1Zm-3,2v-2h2v2h-2Z" />
    </svg>
  )
}
