/**
 * HashtagPixelIcon — vendored from the HackerNoon Pixel Icon Library ("hashtag", regular).
 *
 * Generated by `scripts/vendor-pixel-icons.mjs`. Do not edit by hand.
 * Artwork licensed CC BY 4.0 — see `docs/third-party-notices.md`.
 */
import type { PixelIconProps } from '../types'

export function HashtagPixelIcon({ size = 16, ...props }: PixelIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path d="M17,12V9h6V7H18V4h1V1H17V4H16V7H10V4h1V1H9V4H8V7H3V9H7v3H6v3H1v2H5v3H4v3H6V20H7V17h6v3H12v3h2V20h1V17h6V15H16V12Zm-2,0H14v3H8V12H9V9h6Z" />
    </svg>
  )
}
