/**
 * PausePixelIcon — vendored from the HackerNoon Pixel Icon Library ("pause", regular).
 *
 * Generated by `scripts/vendor-pixel-icons.mjs`. Do not edit by hand.
 * Artwork licensed CC BY 4.0 — see `docs/third-party-notices.md`.
 */
import type { PixelIconProps } from '../types'

export function PausePixelIcon({ size = 16, ...props }: PixelIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path d="m9,1H2v1h-1v20h1v1h7v-1h1V2h-1v-1Zm-1,2v18H3V3h5Z" />
      <path d="m22,2v-1h-7v1h-1v20h1v1h7v-1h1V2h-1Zm-1,1v18h-5V3h5Z" />
    </svg>
  )
}
