/**
 * PlaneDeparturePixelIcon — vendored from the HackerNoon Pixel Icon Library ("plane-departure", regular).
 *
 * Generated by `scripts/vendor-pixel-icons.mjs`. Do not edit by hand.
 * Artwork licensed CC BY 4.0 — see `docs/third-party-notices.md`.
 */
import type { PixelIconProps } from '../types'

export function PlaneDeparturePixelIcon({ size = 16, ...props }: PixelIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <rect x="1" y="18" width="22" height="2" />
      <path d="m19,4v1h-2v1h-2v1h-2v-1h-2v-1h-2v-1h-2v-1h-1v1h-1v1h-1v1h1v1h1v1h1v1h1v1h-1v1h-2v-1h-1v-1H1v3h1v1h1v1h1v1h6v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h1v-4h-4Zm3,3h-1v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-4v-1h-1v-1h-1v-1h-1v-1h1v1h1v1h4v-1h1v-3h-1v-1h-1v-1h-1v-1h2v1h2v1h2v1h4v-1h2v-1h2v-1h2v2Z" />
    </svg>
  )
}
