/**
 * SortPixelIcon — vendored from the HackerNoon Pixel Icon Library ("sort", regular).
 *
 * Generated by `scripts/vendor-pixel-icons.mjs`. Do not edit by hand.
 * Artwork licensed CC BY 4.0 — see `docs/third-party-notices.md`.
 */
import type { PixelIconProps } from '../types'

export function SortPixelIcon({ size = 16, ...props }: PixelIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path d="m19,14v-1H5v1h-1v2h1v1h1v1h1v1h1v1h1v1h1v1h1v1h2v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-2h-1Zm-2,2h-1v1h-1v1h-1v1h-1v1h-2v-1h-1v-1h-1v-1h-1v-1h-1v-1h10v1Z" />
      <path d="m19,8v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-2v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v2h1v1h14v-1h1v-2h-1Zm-2,1H7v-1h1v-1h1v-1h1v-1h1v-1h2v1h1v1h1v1h1v1h1v1Z" />
    </svg>
  )
}
