/**
 * TablePixelIcon — vendored from the HackerNoon Pixel Icon Library ("table", regular).
 *
 * Generated by `scripts/vendor-pixel-icons.mjs`. Do not edit by hand.
 * Artwork licensed CC BY 4.0 — see `docs/third-party-notices.md`.
 */
import type { PixelIconProps } from '../types'

export function TablePixelIcon({ size = 16, ...props }: PixelIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path d="m22,2v-1H2v1h-1v20h1v1h20v-1h1V2h-1Zm-9,14h8v5h-8v-5Zm0-1v-6h8v6h-8Zm0-7V3h8v5h-8Zm-2,1v6H3v-6h8Zm-8-1V3h8v5H3Zm8,8v5H3v-5h8Z" />
    </svg>
  )
}
