/**
 * ThumbtackPixelIcon — vendored from the HackerNoon Pixel Icon Library ("thumbtack", regular).
 *
 * Generated by `scripts/vendor-pixel-icons.mjs`. Do not edit by hand.
 * Artwork licensed CC BY 4.0 — see `docs/third-party-notices.md`.
 */
import type { PixelIconProps } from '../types'

export function ThumbtackPixelIcon({ size = 16, ...props }: PixelIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
      <path d="m18,13v-1h-1v-1h-1v-7h2v-2h-1v-1H7v1h-1v2h2v7h-1v1h-1v1h-1v2h1v1h5v7h2v-7h5v-1h1v-2h-1ZM9,3h6v1h-1v8h1v1h1v1h-8v-1h1v-1h1V4h-1v-1Z" />
    </svg>
  )
}
