from typing import Literal

KnowledgeScope = Literal["demo", "admin", "internal"]

KnowledgeNodeType = Literal[
    "FinancialConcept",
    "Formula",
    "MathConcept",
    "Indicator",
    "TradingStrategy",
    "RiskMetric",
    "PortfolioMetric",
    "BudgetMetric",
    "PersonalFinanceRule",
    "MarketEvent",
    "NewsSignal",
    "MacroSignal",
    "TweetSignal",
    "Asset",
    "Ticker",
    "Sector",
    "Region",
    "Provider",
    "SourceDocument",
    "UserFinancialStateSnapshot",
    "Goal",
    "TransactionCluster",
    "RecurringCommitment",
    "Recommendation",
    "Assumption",
    "Evidence",
    "Model",
    "AgentSkill",
    "AgentRun",
    "CostObservation",
    "TokenUsageObservation",
]

KnowledgeRelationType = Literal[
    "DEFINES",
    "USES_FORMULA",
    "APPLIES_TO",
    "DERIVED_FROM",
    "SUPPORTED_BY",
    "CONTRADICTED_BY",
    "IMPACTS",
    "CAUSES",
    "CORRELATES_WITH",
    "OBSERVED_IN",
    "AFFECTS_ASSET",
    "AFFECTS_SECTOR",
    "AFFECTS_GOAL",
    "GENERATED_RECOMMENDATION",
    "JUSTIFIES",
    "REQUIRES_ASSUMPTION",
    "HAS_CONFIDENCE",
    "HAS_RECENCY",
    "USES_MODEL",
    "USES_SKILL",
    "CONSUMED_TOKENS",
    "COSTS",
    "TRIGGERED_BY",
    "MITIGATES",
    "INCREASES_RISK",
    "DECREASES_RISK",
    "BELONGS_TO_DOMAIN",
    "SUPERSEDES",
    "INVALIDATES",
    "REINFORCES",
    "WEAKENS",
    "SIMILAR_TO",
    "PART_OF",
    "LEADS_TO",
    "HAS_TIME_WINDOW",
]

NODE_TYPES: tuple[str, ...] = tuple(KnowledgeNodeType.__args__)  # type: ignore[attr-defined]
RELATION_TYPES: tuple[str, ...] = tuple(KnowledgeRelationType.__args__)  # type: ignore[attr-defined]

RELATION_WEIGHTS: dict[str, float] = {
    "SUPPORTED_BY": 1.0,
    "CONTRADICTED_BY": 0.98,
    "SUPERSEDES": 0.96,
    "INVALIDATES": 0.96,
    "CAUSES": 0.92,
    "IMPACTS": 0.9,
    "JUSTIFIES": 0.88,
    "REQUIRES_ASSUMPTION": 0.86,
    "AFFECTS_ASSET": 0.84,
    "AFFECTS_SECTOR": 0.82,
    "USES_FORMULA": 0.8,
    "DERIVED_FROM": 0.78,
    "APPLIES_TO": 0.76,
    "CORRELATES_WITH": 0.7,
    "SIMILAR_TO": 0.66,
    "PART_OF": 0.64,
}

SCHEMA_VERSION = "2026-04-26.temporal-graph-v1"
