import type {
  KnowledgeContextBundleInput,
  KnowledgeExplainInput,
  KnowledgeQueryInput,
} from '../../services/knowledge-service-client'

const generatedAt = '2026-04-26T00:00:00.000Z'

export const getDemoKnowledgeStats = (requestId: string) => ({
  ok: true,
  requestId,
  generatedAt,
  backend: 'demo-fixture',
  vectorBackend: 'deterministic-local',
  entityCount: 76,
  relationCount: 32,
  historicalEntityCount: 0,
  historicalRelationCount: 0,
  sourceCounts: {
    'finance-os-curated-seed': 76,
  },
  entityTypeCounts: {
    FinancialConcept: 8,
    Formula: 9,
    RiskMetric: 16,
    BudgetMetric: 9,
    TradingStrategy: 8,
    MacroSignal: 8,
    Model: 1,
    CostObservation: 1,
  },
  relationTypeCounts: {
    USES_FORMULA: 6,
    IMPACTS: 9,
    CONTRADICTED_BY: 2,
    REQUIRES_ASSUMPTION: 4,
    INVALIDATES: 4,
  },
  contradictionCount: 2,
  supersededFactCount: 0,
  dedupeCount: 0,
  ingestCount: 1,
  lastIngestAt: generatedAt,
  lastSuccessfulRebuildAt: generatedAt,
  lastFailureReason: null,
  queryLatencyMs: 3,
  graphTraversalLatencyMs: 1,
  vectorRetrievalLatencyMs: 1,
  fulltextRetrievalLatencyMs: 1,
  contextBundleTokenEstimate: 540,
  rebuildDurationMs: 42,
  fallbackUsageCount: 0,
  storageSizeBytes: 0,
  degraded: false,
  mode: 'demo',
})

export const getDemoKnowledgeSchema = (requestId: string) => ({
  ok: true,
  requestId,
  schemaVersion: '2026-04-26.temporal-graph-v1',
  nodeTypes: [
    'FinancialConcept',
    'Formula',
    'MathConcept',
    'Indicator',
    'TradingStrategy',
    'RiskMetric',
    'PortfolioMetric',
    'BudgetMetric',
    'PersonalFinanceRule',
    'MarketEvent',
    'NewsSignal',
    'MacroSignal',
    'TweetSignal',
    'Asset',
    'Ticker',
    'Sector',
    'Region',
    'Provider',
    'SourceDocument',
    'UserFinancialStateSnapshot',
    'Goal',
    'TransactionCluster',
    'RecurringCommitment',
    'Recommendation',
    'Assumption',
    'Evidence',
    'Model',
    'AgentSkill',
    'AgentRun',
    'CostObservation',
    'TokenUsageObservation',
  ],
  relationTypes: [
    'DEFINES',
    'USES_FORMULA',
    'APPLIES_TO',
    'DERIVED_FROM',
    'SUPPORTED_BY',
    'CONTRADICTED_BY',
    'IMPACTS',
    'CAUSES',
    'CORRELATES_WITH',
    'OBSERVED_IN',
    'AFFECTS_ASSET',
    'AFFECTS_SECTOR',
    'AFFECTS_GOAL',
    'GENERATED_RECOMMENDATION',
    'JUSTIFIES',
    'REQUIRES_ASSUMPTION',
    'HAS_CONFIDENCE',
    'HAS_RECENCY',
    'USES_MODEL',
    'USES_SKILL',
    'CONSUMED_TOKENS',
    'COSTS',
    'TRIGGERED_BY',
    'MITIGATES',
    'INCREASES_RISK',
    'DECREASES_RISK',
    'BELONGS_TO_DOMAIN',
    'SUPERSEDES',
    'INVALIDATES',
    'REINFORCES',
    'WEAKENS',
    'SIMILAR_TO',
    'PART_OF',
    'LEADS_TO',
    'HAS_TIME_WINDOW',
  ],
  temporalFields: [
    'observedAt',
    'validFrom',
    'validTo',
    'invalidatedAt',
    'supersededBy',
    'sourceTimestamp',
    'ingestionTimestamp',
  ],
  selectedProductionBackends: {
    graph: 'neo4j',
    vector: 'qdrant',
    fullText: 'neo4j full-text plus BM25 fallback',
  },
})

const demoEntities = [
  {
    id: 'budgetmetric:cash_drag',
    type: 'BudgetMetric',
    title: 'Cash drag',
    summary: 'Expected return gap caused by excess unallocated cash.',
    confidence: 0.86,
    recency: 1,
    tags: ['cash', 'opportunity-cost'],
  },
  {
    id: 'financialconcept:inflation_adjusted_returns',
    type: 'FinancialConcept',
    title: 'Inflation-adjusted returns',
    summary:
      'Return adjusted for inflation so nominal performance is not mistaken for purchasing-power growth.',
    confidence: 0.88,
    recency: 1,
    tags: ['inflation', 'returns'],
  },
  {
    id: 'riskmetric:lookahead_bias',
    type: 'RiskMetric',
    title: 'Lookahead bias',
    summary: 'Backtest error where the strategy uses information unavailable at the decision time.',
    confidence: 0.9,
    recency: 1,
    tags: ['backtesting', 'risk'],
  },
] as const

const toDemoKnowledgeEntity = (entity: (typeof demoEntities)[number]) => ({
  id: entity.id,
  type: entity.type,
  label: entity.title,
  description: entity.summary,
  source: 'finance-os-curated-seed',
  sourceRef: `demo:${entity.id}`,
  provenance: [
    {
      source: 'finance-os-curated-seed',
      sourceType: 'curated_reference',
      sourceRef: `demo:${entity.id}`,
      confidence: entity.confidence,
    },
  ],
  createdAt: generatedAt,
  updatedAt: generatedAt,
  observedAt: generatedAt,
  validFrom: generatedAt,
  sourceTimestamp: generatedAt,
  ingestionTimestamp: generatedAt,
  confidence: entity.confidence,
  tags: entity.tags,
  scope: 'demo',
  metadata: {},
})

export const getDemoKnowledgeQuery = (input: KnowledgeQueryInput, requestId: string) => ({
  ok: true,
  requestId,
  mode: 'demo',
  query: input.query,
  retrievalMode: input.retrievalMode ?? 'hybrid',
  generatedAt,
  degraded: false,
  fallbackReason: null,
  metrics: {
    queryLatencyMs: 3,
    fulltextRetrievalLatencyMs: 1,
    vectorRetrievalLatencyMs: 1,
    graphTraversalLatencyMs: 1,
    hitCount: demoEntities.length,
    candidateCount: 76,
    maxPathDepth: input.maxPathDepth ?? 3,
  },
  hits: demoEntities.map((entity, index) => ({
    entity: toDemoKnowledgeEntity(entity),
    score: {
      total: 0.92 - index * 0.08,
      fulltext: 0.7 - index * 0.06,
      vector: 0.68 - index * 0.05,
      graph: 0.82 - index * 0.04,
      temporal: 1,
      confidence: entity.confidence,
      provenance: 0.5,
      relationWeight: 0.8 - index * 0.05,
    },
    why: ['demo deterministic match', 'relation-weighted graph traversal', 'curated provenance'],
    relations: [],
    paths: [],
    evidence: [],
    contradictoryEvidence:
      entity.id === 'riskmetric:lookahead_bias' ? [] : [toDemoKnowledgeEntity(demoEntities[2])],
  })),
})

export const getDemoKnowledgeContextBundle = (
  input: KnowledgeContextBundleInput,
  requestId: string
) => ({
  requestId,
  mode: 'demo',
  generatedAt,
  query: input.query,
  maxTokens: input.maxTokens ?? 1800,
  tokenEstimate: 160,
  summary:
    'Cash drag, inflation-adjusted returns and backtesting bias are relevant deterministic seed concepts. Demo mode never calls providers and only enriches advisor reasoning.',
  entities: demoEntities.map(entity => ({
    id: entity.id,
    type: entity.type,
    title: entity.title,
    summary: entity.summary,
    confidence: entity.confidence,
    recency: entity.recency,
    provenanceRefs: [`demo:${entity.id}`],
    why: ['demo deterministic context'],
  })),
  relations: [],
  graphPaths: [],
  evidence: [],
  contradictoryEvidence: [
    {
      id: 'riskmetric:lookahead_bias',
      type: 'RiskMetric',
      title: 'Lookahead bias',
      summary: 'Contradiction check for any technical or backtest-derived claim.',
      confidence: 0.9,
      recency: 1,
      provenanceRefs: ['demo:riskmetric:lookahead_bias'],
      why: ['contradiction guardrail'],
    },
  ],
  assumptions: [],
  unknowns: ['Demo mode has no live personal/provider graph facts.'],
  retrievalExplanation: [
    'Hybrid demo retrieval uses deterministic fixtures.',
    'Deterministic finance-engine remains primary; graph context enriches and challenges.',
  ],
  confidence: 0.88,
  recency: 1,
  provenance: [],
  degraded: false,
  fallbackReason: null,
})

export const getDemoKnowledgeExplain = (input: KnowledgeExplainInput, requestId: string) => ({
  ok: true,
  requestId,
  id: input.id,
  explanation:
    'Demo explanation: the item is part of the deterministic curated seed and is returned by keyword, semantic fixture and graph-neighbor relevance. It is enrichment context only.',
  score: {
    total: 0.82,
    fulltext: 0.7,
    vector: 0.66,
    graph: 0.8,
    temporal: 1,
    confidence: 0.86,
    provenance: 0.5,
    relationWeight: 0.76,
  },
  entity: null,
  relation: null,
  paths: [],
  evidence: [],
  contradictoryEvidence: [],
})
