/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionRouteImport } from './routes/version'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PowensCallbackRouteImport } from './routes/powens/callback'
import { Route as AppSanteRouteImport } from './routes/_app/sante'
import { Route as AppPatrimoineRouteImport } from './routes/_app/patrimoine'
import { Route as AppParametresRouteImport } from './routes/_app/parametres'
import { Route as AppObjectifsRouteImport } from './routes/_app/objectifs'
import { Route as AppMemoireRouteImport } from './routes/_app/memoire'
import { Route as AppMarchesRouteImport } from './routes/_app/marches'
import { Route as AppInvestissementsRouteImport } from './routes/_app/investissements'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppFiscaliteRouteImport } from './routes/_app/fiscalite'
import { Route as AppDepensesRouteImport } from './routes/_app/depenses'
import { Route as AppActualitesRouteImport } from './routes/_app/actualites'
import { Route as AppSignauxIndexRouteImport } from './routes/_app/signaux/index'
import { Route as AppIaIndexRouteImport } from './routes/_app/ia/index'
import { Route as AppSignauxSourcesRouteImport } from './routes/_app/signaux/sources'
import { Route as AppSignauxSocialRouteImport } from './routes/_app/signaux/social'
import { Route as AppSignauxMarchesRouteImport } from './routes/_app/signaux/marches'
import { Route as AppIaTradingLabRouteImport } from './routes/_app/ia/trading-lab'
import { Route as AppIaCoutsRouteImport } from './routes/_app/ia/couts'
import { Route as AppIaChatRouteImport } from './routes/_app/ia/chat'
import { Route as AppIaMemoireIndexRouteImport } from './routes/_app/ia/memoire/index'
import { Route as AppIaMemoireGraphRouteImport } from './routes/_app/ia/memoire/graph'

const VersionRoute = VersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PowensCallbackRoute = PowensCallbackRouteImport.update({
  id: '/powens/callback',
  path: '/powens/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSanteRoute = AppSanteRouteImport.update({
  id: '/sante',
  path: '/sante',
  getParentRoute: () => AppRoute,
} as any)
const AppPatrimoineRoute = AppPatrimoineRouteImport.update({
  id: '/patrimoine',
  path: '/patrimoine',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppObjectifsRoute = AppObjectifsRouteImport.update({
  id: '/objectifs',
  path: '/objectifs',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoireRoute = AppMemoireRouteImport.update({
  id: '/memoire',
  path: '/memoire',
  getParentRoute: () => AppRoute,
} as any)
const AppMarchesRoute = AppMarchesRouteImport.update({
  id: '/marches',
  path: '/marches',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestissementsRoute = AppInvestissementsRouteImport.update({
  id: '/investissements',
  path: '/investissements',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscaliteRoute = AppFiscaliteRouteImport.update({
  id: '/fiscalite',
  path: '/fiscalite',
  getParentRoute: () => AppRoute,
} as any)
const AppDepensesRoute = AppDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AppRoute,
} as any)
const AppActualitesRoute = AppActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => AppRoute,
} as any)
const AppSignauxIndexRoute = AppSignauxIndexRouteImport.update({
  id: '/signaux/',
  path: '/signaux/',
  getParentRoute: () => AppRoute,
} as any)
const AppIaIndexRoute = AppIaIndexRouteImport.update({
  id: '/ia/',
  path: '/ia/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignauxSourcesRoute = AppSignauxSourcesRouteImport.update({
  id: '/signaux/sources',
  path: '/signaux/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppSignauxSocialRoute = AppSignauxSocialRouteImport.update({
  id: '/signaux/social',
  path: '/signaux/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSignauxMarchesRoute = AppSignauxMarchesRouteImport.update({
  id: '/signaux/marches',
  path: '/signaux/marches',
  getParentRoute: () => AppRoute,
} as any)
const AppIaTradingLabRoute = AppIaTradingLabRouteImport.update({
  id: '/ia/trading-lab',
  path: '/ia/trading-lab',
  getParentRoute: () => AppRoute,
} as any)
const AppIaCoutsRoute = AppIaCoutsRouteImport.update({
  id: '/ia/couts',
  path: '/ia/couts',
  getParentRoute: () => AppRoute,
} as any)
const AppIaChatRoute = AppIaChatRouteImport.update({
  id: '/ia/chat',
  path: '/ia/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppIaMemoireIndexRoute = AppIaMemoireIndexRouteImport.update({
  id: '/ia/memoire/',
  path: '/ia/memoire/',
  getParentRoute: () => AppRoute,
} as any)
const AppIaMemoireGraphRoute = AppIaMemoireGraphRouteImport.update({
  id: '/ia/memoire/graph',
  path: '/ia/memoire/graph',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/transactions': typeof TransactionsRoute
  '/version': typeof VersionRoute
  '/actualites': typeof AppActualitesRoute
  '/depenses': typeof AppDepensesRoute
  '/fiscalite': typeof AppFiscaliteRoute
  '/integrations': typeof AppIntegrationsRoute
  '/investissements': typeof AppInvestissementsRoute
  '/marches': typeof AppMarchesRoute
  '/memoire': typeof AppMemoireRoute
  '/objectifs': typeof AppObjectifsRoute
  '/parametres': typeof AppParametresRoute
  '/patrimoine': typeof AppPatrimoineRoute
  '/sante': typeof AppSanteRoute
  '/powens/callback': typeof PowensCallbackRoute
  '/ia/chat': typeof AppIaChatRoute
  '/ia/couts': typeof AppIaCoutsRoute
  '/ia/trading-lab': typeof AppIaTradingLabRoute
  '/signaux/marches': typeof AppSignauxMarchesRoute
  '/signaux/social': typeof AppSignauxSocialRoute
  '/signaux/sources': typeof AppSignauxSourcesRoute
  '/ia/': typeof AppIaIndexRoute
  '/signaux/': typeof AppSignauxIndexRoute
  '/ia/memoire/graph': typeof AppIaMemoireGraphRoute
  '/ia/memoire/': typeof AppIaMemoireIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/transactions': typeof TransactionsRoute
  '/version': typeof VersionRoute
  '/actualites': typeof AppActualitesRoute
  '/depenses': typeof AppDepensesRoute
  '/fiscalite': typeof AppFiscaliteRoute
  '/integrations': typeof AppIntegrationsRoute
  '/investissements': typeof AppInvestissementsRoute
  '/marches': typeof AppMarchesRoute
  '/memoire': typeof AppMemoireRoute
  '/objectifs': typeof AppObjectifsRoute
  '/parametres': typeof AppParametresRoute
  '/patrimoine': typeof AppPatrimoineRoute
  '/sante': typeof AppSanteRoute
  '/powens/callback': typeof PowensCallbackRoute
  '/': typeof AppIndexRoute
  '/ia/chat': typeof AppIaChatRoute
  '/ia/couts': typeof AppIaCoutsRoute
  '/ia/trading-lab': typeof AppIaTradingLabRoute
  '/signaux/marches': typeof AppSignauxMarchesRoute
  '/signaux/social': typeof AppSignauxSocialRoute
  '/signaux/sources': typeof AppSignauxSourcesRoute
  '/ia': typeof AppIaIndexRoute
  '/signaux': typeof AppSignauxIndexRoute
  '/ia/memoire/graph': typeof AppIaMemoireGraphRoute
  '/ia/memoire': typeof AppIaMemoireIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/transactions': typeof TransactionsRoute
  '/version': typeof VersionRoute
  '/_app/actualites': typeof AppActualitesRoute
  '/_app/depenses': typeof AppDepensesRoute
  '/_app/fiscalite': typeof AppFiscaliteRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/investissements': typeof AppInvestissementsRoute
  '/_app/marches': typeof AppMarchesRoute
  '/_app/memoire': typeof AppMemoireRoute
  '/_app/objectifs': typeof AppObjectifsRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/patrimoine': typeof AppPatrimoineRoute
  '/_app/sante': typeof AppSanteRoute
  '/powens/callback': typeof PowensCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/ia/chat': typeof AppIaChatRoute
  '/_app/ia/couts': typeof AppIaCoutsRoute
  '/_app/ia/trading-lab': typeof AppIaTradingLabRoute
  '/_app/signaux/marches': typeof AppSignauxMarchesRoute
  '/_app/signaux/social': typeof AppSignauxSocialRoute
  '/_app/signaux/sources': typeof AppSignauxSourcesRoute
  '/_app/ia/': typeof AppIaIndexRoute
  '/_app/signaux/': typeof AppSignauxIndexRoute
  '/_app/ia/memoire/graph': typeof AppIaMemoireGraphRoute
  '/_app/ia/memoire/': typeof AppIaMemoireIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/healthz'
    | '/login'
    | '/transactions'
    | '/version'
    | '/actualites'
    | '/depenses'
    | '/fiscalite'
    | '/integrations'
    | '/investissements'
    | '/marches'
    | '/memoire'
    | '/objectifs'
    | '/parametres'
    | '/patrimoine'
    | '/sante'
    | '/powens/callback'
    | '/ia/chat'
    | '/ia/couts'
    | '/ia/trading-lab'
    | '/signaux/marches'
    | '/signaux/social'
    | '/signaux/sources'
    | '/ia/'
    | '/signaux/'
    | '/ia/memoire/graph'
    | '/ia/memoire/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/healthz'
    | '/login'
    | '/transactions'
    | '/version'
    | '/actualites'
    | '/depenses'
    | '/fiscalite'
    | '/integrations'
    | '/investissements'
    | '/marches'
    | '/memoire'
    | '/objectifs'
    | '/parametres'
    | '/patrimoine'
    | '/sante'
    | '/powens/callback'
    | '/'
    | '/ia/chat'
    | '/ia/couts'
    | '/ia/trading-lab'
    | '/signaux/marches'
    | '/signaux/social'
    | '/signaux/sources'
    | '/ia'
    | '/signaux'
    | '/ia/memoire/graph'
    | '/ia/memoire'
  id:
    | '__root__'
    | '/_app'
    | '/health'
    | '/healthz'
    | '/login'
    | '/transactions'
    | '/version'
    | '/_app/actualites'
    | '/_app/depenses'
    | '/_app/fiscalite'
    | '/_app/integrations'
    | '/_app/investissements'
    | '/_app/marches'
    | '/_app/memoire'
    | '/_app/objectifs'
    | '/_app/parametres'
    | '/_app/patrimoine'
    | '/_app/sante'
    | '/powens/callback'
    | '/_app/'
    | '/_app/ia/chat'
    | '/_app/ia/couts'
    | '/_app/ia/trading-lab'
    | '/_app/signaux/marches'
    | '/_app/signaux/social'
    | '/_app/signaux/sources'
    | '/_app/ia/'
    | '/_app/signaux/'
    | '/_app/ia/memoire/graph'
    | '/_app/ia/memoire/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  HealthRoute: typeof HealthRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  TransactionsRoute: typeof TransactionsRoute
  VersionRoute: typeof VersionRoute
  PowensCallbackRoute: typeof PowensCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version': {
      id: '/version'
      path: '/version'
      fullPath: '/version'
      preLoaderRoute: typeof VersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/powens/callback': {
      id: '/powens/callback'
      path: '/powens/callback'
      fullPath: '/powens/callback'
      preLoaderRoute: typeof PowensCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sante': {
      id: '/_app/sante'
      path: '/sante'
      fullPath: '/sante'
      preLoaderRoute: typeof AppSanteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patrimoine': {
      id: '/_app/patrimoine'
      path: '/patrimoine'
      fullPath: '/patrimoine'
      preLoaderRoute: typeof AppPatrimoineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/objectifs': {
      id: '/_app/objectifs'
      path: '/objectifs'
      fullPath: '/objectifs'
      preLoaderRoute: typeof AppObjectifsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memoire': {
      id: '/_app/memoire'
      path: '/memoire'
      fullPath: '/memoire'
      preLoaderRoute: typeof AppMemoireRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marches': {
      id: '/_app/marches'
      path: '/marches'
      fullPath: '/marches'
      preLoaderRoute: typeof AppMarchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investissements': {
      id: '/_app/investissements'
      path: '/investissements'
      fullPath: '/investissements'
      preLoaderRoute: typeof AppInvestissementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscalite': {
      id: '/_app/fiscalite'
      path: '/fiscalite'
      fullPath: '/fiscalite'
      preLoaderRoute: typeof AppFiscaliteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/depenses': {
      id: '/_app/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof AppDepensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/actualites': {
      id: '/_app/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof AppActualitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signaux/': {
      id: '/_app/signaux/'
      path: '/signaux'
      fullPath: '/signaux/'
      preLoaderRoute: typeof AppSignauxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia/': {
      id: '/_app/ia/'
      path: '/ia'
      fullPath: '/ia/'
      preLoaderRoute: typeof AppIaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signaux/sources': {
      id: '/_app/signaux/sources'
      path: '/signaux/sources'
      fullPath: '/signaux/sources'
      preLoaderRoute: typeof AppSignauxSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signaux/social': {
      id: '/_app/signaux/social'
      path: '/signaux/social'
      fullPath: '/signaux/social'
      preLoaderRoute: typeof AppSignauxSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signaux/marches': {
      id: '/_app/signaux/marches'
      path: '/signaux/marches'
      fullPath: '/signaux/marches'
      preLoaderRoute: typeof AppSignauxMarchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia/trading-lab': {
      id: '/_app/ia/trading-lab'
      path: '/ia/trading-lab'
      fullPath: '/ia/trading-lab'
      preLoaderRoute: typeof AppIaTradingLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia/couts': {
      id: '/_app/ia/couts'
      path: '/ia/couts'
      fullPath: '/ia/couts'
      preLoaderRoute: typeof AppIaCoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia/chat': {
      id: '/_app/ia/chat'
      path: '/ia/chat'
      fullPath: '/ia/chat'
      preLoaderRoute: typeof AppIaChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia/memoire/': {
      id: '/_app/ia/memoire/'
      path: '/ia/memoire'
      fullPath: '/ia/memoire/'
      preLoaderRoute: typeof AppIaMemoireIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia/memoire/graph': {
      id: '/_app/ia/memoire/graph'
      path: '/ia/memoire/graph'
      fullPath: '/ia/memoire/graph'
      preLoaderRoute: typeof AppIaMemoireGraphRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActualitesRoute: typeof AppActualitesRoute
  AppDepensesRoute: typeof AppDepensesRoute
  AppFiscaliteRoute: typeof AppFiscaliteRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInvestissementsRoute: typeof AppInvestissementsRoute
  AppMarchesRoute: typeof AppMarchesRoute
  AppMemoireRoute: typeof AppMemoireRoute
  AppObjectifsRoute: typeof AppObjectifsRoute
  AppParametresRoute: typeof AppParametresRoute
  AppPatrimoineRoute: typeof AppPatrimoineRoute
  AppSanteRoute: typeof AppSanteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIaChatRoute: typeof AppIaChatRoute
  AppIaCoutsRoute: typeof AppIaCoutsRoute
  AppIaTradingLabRoute: typeof AppIaTradingLabRoute
  AppSignauxMarchesRoute: typeof AppSignauxMarchesRoute
  AppSignauxSocialRoute: typeof AppSignauxSocialRoute
  AppSignauxSourcesRoute: typeof AppSignauxSourcesRoute
  AppIaIndexRoute: typeof AppIaIndexRoute
  AppSignauxIndexRoute: typeof AppSignauxIndexRoute
  AppIaMemoireGraphRoute: typeof AppIaMemoireGraphRoute
  AppIaMemoireIndexRoute: typeof AppIaMemoireIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActualitesRoute: AppActualitesRoute,
  AppDepensesRoute: AppDepensesRoute,
  AppFiscaliteRoute: AppFiscaliteRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInvestissementsRoute: AppInvestissementsRoute,
  AppMarchesRoute: AppMarchesRoute,
  AppMemoireRoute: AppMemoireRoute,
  AppObjectifsRoute: AppObjectifsRoute,
  AppParametresRoute: AppParametresRoute,
  AppPatrimoineRoute: AppPatrimoineRoute,
  AppSanteRoute: AppSanteRoute,
  AppIndexRoute: AppIndexRoute,
  AppIaChatRoute: AppIaChatRoute,
  AppIaCoutsRoute: AppIaCoutsRoute,
  AppIaTradingLabRoute: AppIaTradingLabRoute,
  AppSignauxMarchesRoute: AppSignauxMarchesRoute,
  AppSignauxSocialRoute: AppSignauxSocialRoute,
  AppSignauxSourcesRoute: AppSignauxSourcesRoute,
  AppIaIndexRoute: AppIaIndexRoute,
  AppSignauxIndexRoute: AppSignauxIndexRoute,
  AppIaMemoireGraphRoute: AppIaMemoireGraphRoute,
  AppIaMemoireIndexRoute: AppIaMemoireIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  HealthRoute: HealthRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  TransactionsRoute: TransactionsRoute,
  VersionRoute: VersionRoute,
  PowensCallbackRoute: PowensCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
