import { describe, expect, it } from 'bun:test'
import { createGetDashboardSummaryUseCase } from './create-get-dashboard-summary-use-case'

describe('createGetDashboardSummaryUseCase', () => {
  it('uses normalized balance/category fields and reconstructs daily wealth snapshots', async () => {
    const getSummary = createGetDashboardSummaryUseCase({
      listAccountsWithConnections: async () => [
        {
          powensAccountId: 'acc-1',
          powensConnectionId: 'conn-1',
          source: 'banking',
          provider: 'powens',
          providerConnectionId: 'conn-1',
          providerInstitutionId: 'bank-1',
          providerInstitutionName: 'Bank 1',
          accountName: 'Main account',
          accountCurrency: 'EUR',
          accountType: 'checking',
          enabled: true,
          accountBalance: '42.50',
          connectionStatus: 'connected',
          lastSyncAttemptAt: null,
          lastSyncAt: null,
          lastSuccessAt: null,
          lastFailedAt: null,
          lastError: null,
          syncMetadata: null,
        },
      ],
      listAssets: async () => [
        {
          assetId: 101,
          assetType: 'cash',
          origin: 'provider',
          source: 'banking',
          provider: 'powens',
          providerConnectionId: 'conn-1',
          providerInstitutionName: 'Bank 1',
          powensConnectionId: 'conn-1',
          powensAccountId: 'acc-1',
          name: 'Main account',
          currency: 'EUR',
          valuation: '42.50',
          valuationAsOf: new Date('2026-03-23T00:00:00.000Z'),
          enabled: true,
          metadata: null,
        },
        {
          assetId: 102,
          assetType: 'investment',
          origin: 'manual',
          source: 'manual',
          provider: null,
          providerConnectionId: null,
          providerInstitutionName: null,
          powensConnectionId: null,
          powensAccountId: null,
          name: 'World ETF',
          currency: 'EUR',
          valuation: '10.00',
          valuationAsOf: null,
          enabled: true,
          metadata: {
            note: 'Static manual asset',
          },
        },
      ],
      listInvestmentPositions: async () => [
        {
          positionId: 501,
          positionKey: 'manual-world-etf-open',
          assetId: 102,
          powensAccountId: null,
          powensConnectionId: null,
          source: 'manual',
          provider: null,
          providerConnectionId: null,
          providerPositionId: null,
          assetName: 'World ETF',
          accountName: null,
          name: 'World ETF - CTO',
          currency: 'EUR',
          quantity: '12.34560000',
          costBasis: '8.40',
          costBasisSource: 'minimal',
          currentValue: '10.00',
          lastKnownValue: '9.85',
          openedAt: new Date('2025-04-01T00:00:00.000Z'),
          closedAt: null,
          valuedAt: new Date('2026-03-23T00:00:00.000Z'),
          lastSyncedAt: new Date('2026-03-23T00:30:00.000Z'),
          metadata: {
            strategy: 'buy_and_hold',
          },
        },
      ],
      getFlowTotals: async () => ({
        income: '100.00',
        expenses: '25.40',
      }),
      listDailyNetFlows: async () => [
        {
          bookingDate: '2026-03-22',
          netAmount: '-2.00',
        },
        {
          bookingDate: '2026-03-23',
          netAmount: '5.00',
        },
      ],
      listTopExpenseGroups: async () => [
        {
          category: 'Unknown',
          merchant: 'Coffee Shop Downtown',
          total: '25.40',
          count: 2,
        },
      ],
      now: () => new Date('2026-03-23T12:00:00.000Z'),
    })

    await expect(getSummary('7d')).resolves.toEqual({
      range: '7d',
      totals: {
        balance: 52.5,
        incomes: 100,
        expenses: 25.4,
      },
      connections: [
        {
          powensConnectionId: 'conn-1',
          source: 'banking',
          provider: 'powens',
          providerConnectionId: 'conn-1',
          providerInstitutionId: 'bank-1',
          providerInstitutionName: 'Bank 1',
          status: 'connected',
          lastSyncAttemptAt: null,
          lastSyncAt: null,
          lastSuccessAt: null,
          lastFailedAt: null,
          lastError: null,
          syncMetadata: null,
          balance: 42.5,
          accountCount: 1,
        },
      ],
      accounts: [
        {
          powensAccountId: 'acc-1',
          powensConnectionId: 'conn-1',
          name: 'Main account',
          currency: 'EUR',
          type: 'checking',
          enabled: true,
          balance: 42.5,
        },
      ],
      assets: [
        {
          assetId: 101,
          type: 'cash',
          origin: 'provider',
          source: 'banking',
          provider: 'powens',
          providerConnectionId: 'conn-1',
          providerInstitutionName: 'Bank 1',
          powensConnectionId: 'conn-1',
          powensAccountId: 'acc-1',
          name: 'Main account',
          currency: 'EUR',
          valuation: 42.5,
          valuationAsOf: '2026-03-23T00:00:00.000Z',
          enabled: true,
          metadata: null,
        },
        {
          assetId: 102,
          type: 'investment',
          origin: 'manual',
          source: 'manual',
          provider: null,
          providerConnectionId: null,
          providerInstitutionName: null,
          powensConnectionId: null,
          powensAccountId: null,
          name: 'World ETF',
          currency: 'EUR',
          valuation: 10,
          valuationAsOf: null,
          enabled: true,
          metadata: {
            note: 'Static manual asset',
          },
        },
      ],
      positions: [
        {
          positionId: 501,
          positionKey: 'manual-world-etf-open',
          assetId: 102,
          powensAccountId: null,
          powensConnectionId: null,
          source: 'manual',
          provider: null,
          providerConnectionId: null,
          providerPositionId: null,
          assetName: 'World ETF',
          accountName: null,
          name: 'World ETF - CTO',
          currency: 'EUR',
          quantity: 12.3456,
          costBasis: 8.4,
          costBasisSource: 'minimal',
          currentValue: 10,
          lastKnownValue: 9.85,
          openedAt: '2025-04-01T00:00:00.000Z',
          closedAt: null,
          valuedAt: '2026-03-23T00:00:00.000Z',
          lastSyncedAt: '2026-03-23T00:30:00.000Z',
          enabled: true,
          metadata: {
            strategy: 'buy_and_hold',
          },
        },
      ],
      dailyWealthSnapshots: [
        {
          date: '2026-03-17',
          balance: 49.5,
        },
        {
          date: '2026-03-18',
          balance: 49.5,
        },
        {
          date: '2026-03-19',
          balance: 49.5,
        },
        {
          date: '2026-03-20',
          balance: 49.5,
        },
        {
          date: '2026-03-21',
          balance: 49.5,
        },
        {
          date: '2026-03-22',
          balance: 47.5,
        },
        {
          date: '2026-03-23',
          balance: 52.5,
        },
      ],
      topExpenseGroups: [
        {
          label: 'Unknown - Coffee Shop Downtown',
          category: 'Unknown',
          merchant: 'Coffee Shop Downtown',
          total: 25.4,
          count: 2,
        },
      ],
    })
  })
})
