import type { DashboardMarketsOverviewResponse } from './types'

export const getDemoMarketsOverview = (): DashboardMarketsOverviewResponse => {
  return {
    source: 'demo_fixture',
    dataset: {
      version: 'markets-fixture-pack:2026-04-10',
      source: 'demo_fixture',
      mode: 'demo',
      isDemoData: true,
    },
    requestId: 'demo-markets-request',
    generatedAt: '2026-04-10T06:45:00.000Z',
    freshness: {
      lastSuccessAt: '2026-04-10T06:40:00.000Z',
      stale: false,
      staleAgeSeconds: 300,
      staleAfterMinutes: 960,
      degradedReason: null,
    },
    summary: {
      headline: 'Leadership encore constructif, mais sélectif.',
      tone: 'opportunity',
      badge: 'Overlay US actif',
      openCount: 0,
      closedCount: 14,
      positiveCount: 12,
      negativeCount: 2,
      primarySourceLabel: 'EODHD + Twelve Data + FRED',
    },
    panorama: {
      items: [
        {
          instrumentId: 'spy-us',
          label: 'S&P 500 (SPY)',
          shortLabel: 'S&P 500',
          symbol: 'SPY',
          assetClass: 'etf',
          region: 'us',
          exchange: 'NYSE Arca',
          currency: 'USD',
          proxyLabel: 'ETF proxy',
          tags: ['panorama', 'us', 'equities'],
          price: 536.2,
          previousClose: 531.1,
          dayChangePct: 0.96,
          weekChangePct: 1.7,
          monthChangePct: 4.6,
          ytdChangePct: 8.2,
          history: [
            { date: '2026-03-01', value: 510, provider: 'eodhd' },
            { date: '2026-03-04', value: 518, provider: 'eodhd' },
            { date: '2026-03-07', value: 526, provider: 'eodhd' },
            { date: '2026-03-10', value: 536.2, provider: 'twelve_data' },
          ],
          source: {
            provider: 'twelve_data',
            baselineProvider: 'eodhd',
            overlayProvider: 'twelve_data',
            mode: 'intraday',
            delayLabel: 'Overlay US plus frais',
            reason: 'Overlay Twelve Data actif sur symbole US éligible.',
            quoteDate: '2026-04-09',
            quoteAsOf: '2026-04-10T06:35:00.000Z',
            capturedAt: '2026-04-10T06:45:00.000Z',
            freshnessMinutes: 10,
            isDelayed: false,
          },
          marketSession: {
            state: 'closed',
            isOpen: false,
            label: 'Marché fermé',
          },
        },
        {
          instrumentId: 'qqq-us',
          label: 'Nasdaq 100 (QQQ)',
          shortLabel: 'Nasdaq 100',
          symbol: 'QQQ',
          assetClass: 'etf',
          region: 'us',
          exchange: 'NASDAQ',
          currency: 'USD',
          proxyLabel: 'ETF proxy',
          tags: ['panorama', 'us', 'growth'],
          price: 462.7,
          previousClose: 457.8,
          dayChangePct: 1.07,
          weekChangePct: 2.1,
          monthChangePct: 5.8,
          ytdChangePct: 10.4,
          history: [
            { date: '2026-03-01', value: 430, provider: 'eodhd' },
            { date: '2026-03-04', value: 441, provider: 'eodhd' },
            { date: '2026-03-07', value: 451, provider: 'eodhd' },
            { date: '2026-03-10', value: 462.7, provider: 'twelve_data' },
          ],
          source: {
            provider: 'twelve_data',
            baselineProvider: 'eodhd',
            overlayProvider: 'twelve_data',
            mode: 'intraday',
            delayLabel: 'Overlay US plus frais',
            reason: 'Overlay Twelve Data actif sur symbole US éligible.',
            quoteDate: '2026-04-09',
            quoteAsOf: '2026-04-10T06:35:00.000Z',
            capturedAt: '2026-04-10T06:45:00.000Z',
            freshnessMinutes: 10,
            isDelayed: false,
          },
          marketSession: {
            state: 'closed',
            isOpen: false,
            label: 'Marché fermé',
          },
        },
        {
          instrumentId: 'cw8-pa',
          label: 'MSCI World PEA (CW8)',
          shortLabel: 'MSCI World',
          symbol: 'CW8',
          assetClass: 'etf',
          region: 'world',
          exchange: 'Euronext Paris',
          currency: 'EUR',
          proxyLabel: 'ETF monde',
          tags: ['panorama', 'pea', 'world'],
          price: 546.8,
          previousClose: 544.3,
          dayChangePct: 0.46,
          weekChangePct: 1.4,
          monthChangePct: 4.1,
          ytdChangePct: 7.8,
          history: [
            { date: '2026-03-01', value: 521, provider: 'eodhd' },
            { date: '2026-03-04', value: 529, provider: 'eodhd' },
            { date: '2026-03-07', value: 538, provider: 'eodhd' },
            { date: '2026-03-10', value: 546.8, provider: 'eodhd' },
          ],
          source: {
            provider: 'eodhd',
            baselineProvider: 'eodhd',
            overlayProvider: null,
            mode: 'eod',
            delayLabel: 'Clôture EOD',
            reason: 'Source primaire EODHD EOD.',
            quoteDate: '2026-04-09',
            quoteAsOf: '2026-04-09T21:00:00.000Z',
            capturedAt: '2026-04-10T06:45:00.000Z',
            freshnessMinutes: 540,
            isDelayed: true,
          },
          marketSession: {
            state: 'closed',
            isOpen: false,
            label: 'Marché fermé',
          },
        },
      ],
    },
    macro: {
      items: [
        {
          seriesId: 'FEDFUNDS',
          label: 'Fed funds',
          shortLabel: 'Fed funds',
          group: 'rates',
          unit: 'percent',
          description: 'Taux directeur effectif de la Fed.',
          latestValue: 4.5,
          previousValue: 4.5,
          change: 0,
          changePct: 0,
          changeDirection: 'flat',
          displayValue: '4,50 %',
          comparisonLabel: 'Vs observation précédente',
          comparisonValue: '+0,00 %',
          observationDate: '2026-03-01',
          history: [
            { date: '2025-10-01', value: 4.75 },
            { date: '2025-12-01', value: 4.5 },
            { date: '2026-03-01', value: 4.5 },
          ],
          source: {
            provider: 'fred',
            freshnessLabel: 'Observation du 2026-03-01',
            observationCount: 3,
          },
        },
        {
          seriesId: 'T10Y2Y',
          label: 'Spread 10Y-2Y',
          shortLabel: '10Y-2Y',
          group: 'rates',
          unit: 'spread',
          description: 'Pente 10 ans moins 2 ans.',
          latestValue: 0.18,
          previousValue: 0.19,
          change: -0.01,
          changePct: -5.26,
          changeDirection: 'down',
          displayValue: '0,18 %',
          comparisonLabel: 'Vs observation précédente',
          comparisonValue: '-0,01 %',
          observationDate: '2026-03-31',
          history: [
            { date: '2026-03-24', value: 0.16 },
            { date: '2026-03-27', value: 0.18 },
            { date: '2026-03-31', value: 0.18 },
          ],
          source: {
            provider: 'fred',
            freshnessLabel: 'Observation du 2026-03-31',
            observationCount: 3,
          },
        },
        {
          seriesId: 'CPIAUCSL',
          label: 'Inflation US CPI',
          shortLabel: 'Inflation CPI',
          group: 'inflation',
          unit: 'percent',
          description: 'Indice CPI urbain, transformé en glissement annuel.',
          latestValue: 2.05,
          previousValue: 2.34,
          change: -0.29,
          changePct: -12.39,
          changeDirection: 'down',
          displayValue: '2,05 %',
          comparisonLabel: 'Variation du régime',
          comparisonValue: '-0,29 %',
          observationDate: '2026-03-01',
          history: [
            { date: '2025-01-01', value: 315.1 },
            { date: '2026-02-01', value: 323.4 },
            { date: '2026-03-01', value: 323.7 },
          ],
          source: {
            provider: 'fred',
            freshnessLabel: 'Observation du 2026-03-01',
            observationCount: 3,
          },
        },
      ],
    },
    watchlist: {
      items: [],
      groups: [
        {
          id: 'global',
          label: 'Panorama global',
          itemIds: ['spy-us', 'qqq-us', 'cw8-pa'],
        },
        {
          id: 'pea',
          label: 'PEA / Euronext',
          itemIds: ['cw8-pa', 'air-pa', 'mc-pa'],
        },
      ],
    },
    signals: {
      items: [
        {
          id: 'rates-high',
          title: 'Les taux courts restent élevés',
          detail: "Le coût du capital reste contraignant pour les actifs longs.",
          tone: 'risk',
          severity: 'high',
          evidence: ['Fed funds: 4,50 %'],
          dataRefs: ['macro: FEDFUNDS'],
        },
        {
          id: 'inflation-cooling',
          title: "L'inflation ralentit",
          detail: 'Le CPI annuel se tasse, ce qui ouvre un peu d’oxygène sur la duration.',
          tone: 'opportunity',
          severity: 'medium',
          evidence: ['Inflation CPI YoY: 2,05 %'],
          dataRefs: ['macro: CPIAUCSL'],
        },
      ],
    },
    contextBundle: {
      schemaVersion: '2026-04-10',
      generatedAt: '2026-04-10T06:45:00.000Z',
      coverageSummary: {
        instrumentCount: 3,
        macroSeriesCount: 3,
        providers: [
          { provider: 'eodhd', role: 'prices', coverageCount: 3, freshnessLabel: 'EODHD: fixture EOD' },
          { provider: 'twelve_data', role: 'overlay', coverageCount: 2, freshnessLabel: 'Twelve Data: overlay US actif' },
          { provider: 'fred', role: 'macro', coverageCount: 3, freshnessLabel: 'FRED: séries officielles' },
        ],
      },
      quoteFreshness: {
        intradayCount: 2,
        delayedCount: 0,
        eodCount: 1,
        staleCount: 0,
      },
      keyMovers: {
        gainers: [
          { instrumentId: 'qqq-us', label: 'Nasdaq 100', dayChangePct: 1.07 },
          { instrumentId: 'spy-us', label: 'S&P 500', dayChangePct: 0.96 },
        ],
        losers: [{ instrumentId: 'cw8-pa', label: 'MSCI World', dayChangePct: 0.46 }],
      },
      marketBreadth: {
        positiveCount: 3,
        negativeCount: 0,
        flatCount: 0,
        strongestRegion: 'us',
      },
      marketRegimeHints: ['Les taux courts restent élevés', "L'inflation ralentit"],
      macroRegime: {
        rates: ['Taux courts restrictifs', 'Courbe positive'],
        inflation: ['Inflation en zone plus calme', 'Désinflation en cours'],
        labor: ["Marché de l'emploi encore tendu", 'Chômage stable ou en baisse'],
      },
      ratesSummary: {
        fedFunds: 4.5,
        sofr: 4.29,
        ust2y: 4.06,
        ust10y: 4.24,
        spread10y2y: 0.18,
      },
      inflationSummary: {
        cpiYoY: 2.05,
        direction: 'cooling',
      },
      laborSummary: {
        unemploymentRate: 4.3,
        direction: 'softening',
      },
      riskFlags: ['Les taux courts restent élevés'],
      anomalies: [],
      warnings: [],
      watchlistHighlights: [
        { instrumentId: 'qqq-us', label: 'Nasdaq 100', summary: 'Variation jour +1,07 %.' },
        { instrumentId: 'spy-us', label: 'S&P 500', summary: 'Variation jour +0,96 %.' },
      ],
      providerProvenance: [
        { provider: 'eodhd', label: 'EODHD', role: 'prices', freshnessLabel: 'EODHD: fixture EOD', note: 'Source primaire EOD / différée sur la watchlist globale.' },
        { provider: 'twelve_data', label: 'Twelve Data', role: 'overlay', freshnessLabel: 'Twelve Data: overlay US actif', note: 'Overlay US optionnel lorsque plus frais.' },
        { provider: 'fred', label: 'FRED', role: 'macro', freshnessLabel: 'FRED: séries officielles', note: 'Source macro officielle.' },
      ],
      confidence: {
        level: 'high',
        score: 88,
        caveats: [],
      },
    },
    providers: [
      {
        provider: 'eodhd',
        label: 'EODHD',
        role: 'prices',
        enabled: true,
        status: 'healthy',
        lastSuccessAt: '2026-04-10T06:40:00.000Z',
        lastAttemptAt: '2026-04-10T06:40:00.000Z',
        lastFailureAt: null,
        lastErrorCode: null,
        lastErrorMessage: null,
        lastFetchedCount: 3,
        successCount: 1,
        failureCount: 0,
        skippedCount: 0,
        freshnessLabel: 'EODHD: fixture EOD',
      },
      {
        provider: 'twelve_data',
        label: 'Twelve Data',
        role: 'overlay',
        enabled: true,
        status: 'healthy',
        lastSuccessAt: '2026-04-10T06:40:00.000Z',
        lastAttemptAt: '2026-04-10T06:40:00.000Z',
        lastFailureAt: null,
        lastErrorCode: null,
        lastErrorMessage: null,
        lastFetchedCount: 2,
        successCount: 1,
        failureCount: 0,
        skippedCount: 0,
        freshnessLabel: 'Twelve Data: overlay US actif',
      },
      {
        provider: 'fred',
        label: 'FRED',
        role: 'macro',
        enabled: true,
        status: 'healthy',
        lastSuccessAt: '2026-04-10T06:40:00.000Z',
        lastAttemptAt: '2026-04-10T06:40:00.000Z',
        lastFailureAt: null,
        lastErrorCode: null,
        lastErrorMessage: null,
        lastFetchedCount: 3,
        successCount: 1,
        failureCount: 0,
        skippedCount: 0,
        freshnessLabel: 'FRED: séries officielles',
      },
    ],
  }
}
