import type {
  ExternalInvestmentCashFlow,
  ExternalInvestmentContextBundle,
  ExternalInvestmentListResponse,
  ExternalInvestmentPosition,
  ExternalInvestmentStatusResponse,
  ExternalInvestmentSummaryResponse,
  ExternalInvestmentSyncRunsResponse,
  ExternalInvestmentTrade,
} from './types'

export const EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT = '2026-04-09T12:00:00.000Z'

export const getDemoExternalInvestmentBundle = (): ExternalInvestmentContextBundle => ({
  schemaVersion: '2026-05-01',
  generatedAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
  providerCoverage: [
    {
      provider: 'ibkr',
      configured: true,
      status: 'healthy',
      lastSuccessAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      lastAttemptAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      stale: false,
      degradedReasons: [],
    },
    {
      provider: 'binance',
      configured: true,
      status: 'degraded',
      lastSuccessAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      lastAttemptAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      stale: false,
      degradedReasons: ['VALUATION_PARTIAL'],
    },
  ],
  totalKnownValue: 18420.5,
  unknownValuePositionCount: 1,
  allocationByAssetClass: [
    { key: 'etf', value: 13250.5, weightPct: 71.93 },
    { key: 'equity', value: 3170, weightPct: 17.21 },
    { key: 'stablecoin', value: 2000, weightPct: 10.86 },
  ],
  allocationByProvider: [
    { key: 'ibkr', value: 16420.5, weightPct: 89.14 },
    { key: 'binance', value: 2000, weightPct: 10.86 },
  ],
  allocationByAccount: [
    { key: 'ibkr:demo', label: 'Compte IBKR Flex', value: 16420.5, weightPct: 89.14 },
    { key: 'binance:spot', label: 'Binance Spot', value: 2000, weightPct: 10.86 },
  ],
  allocationByCurrency: [
    { key: 'EUR', value: 16420.5, weightPct: 89.14 },
    { key: 'USDT', value: 2000, weightPct: 10.86 },
  ],
  topConcentrations: [
    {
      positionKey: 'demo-ibkr-cw8',
      label: 'Amundi MSCI World',
      provider: 'ibkr',
      value: 13250.5,
      weightPct: 71.93,
    },
  ],
  cryptoExposure: { value: 0, weightPct: 0, unknownValueCount: 1 },
  stablecoinExposure: { value: 2000, weightPct: 10.86, unknownValueCount: 0 },
  cashDrag: { cashLikeValue: 0, weightPct: 0, note: 'Provider-reported cash only.' },
  recentTradesSummary: { count: 2, byProvider: { ibkr: 2 } },
  recentCashFlowsSummary: { count: 2, byType: { deposit: 1, withdrawal: 1 } },
  feesSummary: { knownFees: 3.2, currency: 'EUR', unknownFeeCount: 0 },
  pnlSummary: { realizedKnown: null, unrealizedKnown: 720.5, unknownPnlCount: 1 },
  unknownCostBasisWarnings: ['BTC cost basis is unknown from Spot balance data.'],
  missingMarketDataWarnings: ['BTC has no persisted EUR valuation in the demo fixture.'],
  staleDataWarnings: [],
  fxAssumptions: ['Dashboard reads do not call market data or providers.'],
  riskFlags: ['UNKNOWN_VALUATION: 1 position has unknown valuation.'],
  opportunityFlags: [],
  assumptions: ['Demo external investment data is deterministic and local.'],
  confidence: 'medium',
  provenance: [
    { provider: 'ibkr', connectionId: 'ibkr:flex', positionCount: 1 },
    { provider: 'binance', connectionId: 'binance:spot', positionCount: 1 },
  ],
})

export const getDemoExternalInvestmentStatus = (): ExternalInvestmentStatusResponse => ({
  requestId: 'demo-external-investments',
  mode: 'demo',
  source: 'demo_fixture',
  enabled: true,
  safeModeActive: false,
  providerEnabled: { ibkr: true, binance: true },
  backlogCount: 0,
  connections: [
    {
      id: 1,
      provider: 'ibkr',
      providerConnectionId: 'ibkr:flex',
      accountAlias: 'Compte IBKR Flex',
      enabled: true,
      status: 'connected',
      credentialStatus: 'configured',
      maskedMetadata: { maskedSecretRefs: { flexToken: '********demo' } },
      lastSyncStatus: 'OK',
      lastSyncReasonCode: 'SUCCESS',
      lastSyncAttemptAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      lastSyncAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      lastSuccessAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      lastFailedAt: null,
      lastErrorCode: null,
      lastErrorMessage: null,
      syncMetadata: { rowCounts: { positions: 1, rawImports: 3 } },
      archivedAt: null,
      updatedAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
    },
    {
      id: 2,
      provider: 'binance',
      providerConnectionId: 'binance:spot',
      accountAlias: 'Binance Spot',
      enabled: true,
      status: 'degraded',
      credentialStatus: 'configured',
      maskedMetadata: { maskedSecretRefs: { apiKey: '********demo' } },
      lastSyncStatus: 'PARTIAL',
      lastSyncReasonCode: 'VALUATION_PARTIAL',
      lastSyncAttemptAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      lastSyncAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      lastSuccessAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      lastFailedAt: null,
      lastErrorCode: null,
      lastErrorMessage: null,
      syncMetadata: { rowCounts: { positions: 2, rawImports: 4 } },
      archivedAt: null,
      updatedAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
    },
  ],
  health: getDemoExternalInvestmentBundle().providerCoverage.map(item => ({
    provider: item.provider,
    enabled: true,
    status: item.status,
    lastSuccessAt: item.lastSuccessAt,
    lastAttemptAt: item.lastAttemptAt,
    lastFailureAt: null,
    lastErrorCode: null,
    lastErrorMessage: null,
    lastRequestId: 'demo-external-investments',
    lastDurationMs: 420,
    lastRawImportCount: item.provider === 'ibkr' ? 3 : 4,
    lastNormalizedRowCount: item.provider === 'ibkr' ? 2 : 3,
    successCount: 1,
    failureCount: 0,
    skippedCount: 0,
    metadata: {},
  })),
})

export const getDemoExternalInvestmentPositions =
  (): ExternalInvestmentListResponse<ExternalInvestmentPosition> => ({
    requestId: 'demo-external-investments',
    source: 'demo_fixture',
    items: [
      {
        id: 1,
        provider: 'ibkr',
        connectionId: 1,
        providerConnectionId: 'ibkr:flex',
        accountExternalId: 'U****123',
        accountAlias: 'Compte IBKR Flex',
        instrumentKey: 'ibkr:123456',
        positionKey: 'demo-ibkr-cw8',
        providerPositionId: 'ibkr:123456',
        name: 'Amundi MSCI World',
        symbol: 'CW8',
        assetClass: 'etf',
        quantity: 42,
        freeQuantity: null,
        lockedQuantity: null,
        currency: 'EUR',
        providerValue: 13250.5,
        normalizedValue: 13250.5,
        valueCurrency: 'EUR',
        valueSource: 'provider_reported',
        valueAsOf: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
        costBasis: 12530,
        costBasisCurrency: 'EUR',
        realizedPnl: null,
        unrealizedPnl: 720.5,
        metadata: {},
        assumptions: [],
        degradedReasons: [],
        sourceConfidence: 'high',
        firstSeenAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
        lastSeenAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
        updatedAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      },
      {
        id: 2,
        provider: 'binance',
        connectionId: 2,
        providerConnectionId: 'binance:spot',
        accountExternalId: 'binance:spot',
        accountAlias: 'Binance Spot',
        instrumentKey: 'binance:asset:BTC',
        positionKey: 'demo-binance-btc',
        providerPositionId: 'BTC',
        name: 'Bitcoin',
        symbol: 'BTC',
        assetClass: 'crypto',
        quantity: 0.045,
        freeQuantity: 0.045,
        lockedQuantity: 0,
        currency: 'BTC',
        providerValue: null,
        normalizedValue: null,
        valueCurrency: null,
        valueSource: 'unknown',
        valueAsOf: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
        costBasis: null,
        costBasisCurrency: null,
        realizedPnl: null,
        unrealizedPnl: null,
        metadata: {},
        assumptions: ['No EUR valuation is inferred without cached market data.'],
        degradedReasons: ['VALUATION_PARTIAL', 'unknown_cost_basis'],
        sourceConfidence: 'high',
        firstSeenAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
        lastSeenAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
        updatedAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      },
    ],
  })

export const getDemoExternalInvestmentTrades =
  (): ExternalInvestmentListResponse<ExternalInvestmentTrade> => ({
    requestId: 'demo-external-investments',
    source: 'demo_fixture',
    items: [
      {
        id: 1,
        provider: 'ibkr',
        providerConnectionId: 'ibkr:flex',
        accountExternalId: 'U****123',
        symbol: 'CW8',
        side: 'buy',
        quantity: 2,
        price: 315.2,
        grossAmount: 630.4,
        netAmount: 631.4,
        currency: 'EUR',
        feeAmount: 1,
        feeAsset: 'EUR',
        tradedAt: '2026-04-08T10:00:00.000Z',
        sourceConfidence: 'high',
      },
    ],
  })

export const getDemoExternalInvestmentCashFlows =
  (): ExternalInvestmentListResponse<ExternalInvestmentCashFlow> => ({
    requestId: 'demo-external-investments',
    source: 'demo_fixture',
    items: [
      {
        id: 1,
        provider: 'binance',
        providerConnectionId: 'binance:spot',
        accountExternalId: 'binance:spot',
        type: 'deposit',
        asset: 'USDT',
        amount: 2000,
        currency: 'USDT',
        feeAmount: null,
        feeAsset: null,
        occurredAt: '2026-04-07T08:00:00.000Z',
        sourceConfidence: 'high',
      },
    ],
  })

export const getDemoExternalInvestmentSummary = (): ExternalInvestmentSummaryResponse => ({
  requestId: 'demo-external-investments',
  source: 'demo_fixture',
  enabled: true,
  safeModeActive: false,
  providerEnabled: { ibkr: true, binance: true },
  generatedAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
  dataStatus: { status: 'ready', message: null },
  status: getDemoExternalInvestmentStatus(),
  bundle: getDemoExternalInvestmentBundle(),
  latestBundleMeta: {
    schemaVersion: '2026-05-01',
    generatedAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
    requestId: 'demo-external-investments',
    staleAfterMinutes: 1440,
    updatedAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
  },
  positionCount: getDemoExternalInvestmentPositions().items.length,
})

export const getDemoExternalInvestmentSyncRuns = (): ExternalInvestmentSyncRunsResponse => ({
  requestId: 'demo-external-investments',
  source: 'demo_fixture',
  items: [
    {
      id: 'demo-external-investments-sync',
      requestId: 'demo-external-investments',
      provider: 'ibkr',
      providerConnectionId: 'ibkr:flex',
      triggerSource: 'manual',
      status: 'success',
      startedAt: '2026-04-09T11:59:00.000Z',
      finishedAt: EXTERNAL_INVESTMENTS_DEMO_GENERATED_AT,
      durationMs: 60000,
      errorCode: null,
      errorMessage: null,
      rowCounts: { positions: 1, trades: 1, cashFlows: 0, rawImports: 3 },
      degradedReasons: [],
    },
  ],
})
